{% set name = "goreleaser" %}
{% set version = "2.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/goreleaser/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fed388873810b76db1933fdf862bc43fa12f2b5b19c492e35ed6bc396d16a307

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - goreleaser --help

about:
  home: https://goreleaser.com/
  dev_url: https://github.com/goreleaser/goreleaser/
  license: MIT
  license_file:
    - LICENSE.md
    - license-files/
  summary: Release engineering, simplified

extra:
  recipe-maintainers:
    - apcamargo
