{% set name = "goreleaser" %}
{% set version = "2.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/goreleaser/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 521d731821cac14e0e8022d4aa9e4463cc298d3e7efd89df9d4ac1aad26714f6

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - goreleaser --help

about:
  home: https://goreleaser.com/
  dev_url: https://github.com/goreleaser/goreleaser/
  license: MIT
  license_file:
    - LICENSE.md
    - license-files/
  summary: Release engineering, simplified

extra:
  recipe-maintainers:
    - apcamargo
