{% set name = "goreleaser" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/goreleaser/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c11c7c14c9802018c9eabc373a1f35994d65731619f2ecc002c9424d7368fdc5

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - goreleaser --help

about:
  home: https://goreleaser.com/
  dev_url: https://github.com/goreleaser/goreleaser/
  license: MIT
  license_file:
    - LICENSE.md
    - license-files/
  summary: Release engineering, simplified

extra:
  recipe-maintainers:
    - apcamargo
